version: '2'
services:
    optimizationjob-app:
        image: optimizationjob
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://optimizationjob-mysql:3306/optimizationjob?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    optimizationjob-mysql:
        extends:
            file: mysql.yml
            service: optimizationjob-mysql
